### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by OysterD3** [manyuanrong/deno_mongo#53]
How can I handle query error?
I have created a unique index, but how can I detect whether the error code is 11000

**Comment by lucacasonato** [comment]
You can not handle errors at the moment as they are panics inside of Rust code.

@manyuanrong I think errors should be propagated to JavaScript and thrown there so they can be handled. What do you think? I can implement this, but I want to wait for https://github.com/denoland/deno/pull/6398 to land because it would make this significantly easier.

**Comment by manyuanrong** [comment]
> @manyuanrong我认为错误应该传播到JavaScript并扔在那里，以便可以进行处理。你怎么看？我可以实现它，但是我想等待[denoland / deno＃6398](https://github.com/denoland/deno/pull/6398)登陆，因为这将使此操作变得更加容易。

Yes, that's what I always expected
