### ISSUE TITLE
.dll files are missing in multiple releases

### ISSUE THREAD

**Issue by jeroenptrs** [manyuanrong/deno_mongo#98]
- v0.10.1
- v0.10.0
- v0.9.2

Are all missing `deno_mongo.dll`

As a library author you should always include all assets needed, this is breaking usage for your windows userbase.

Additionally: v0.10.1 initialization is pointing to v0.10.0 assets.

**Comment by manyuanrong** [comment]
Because the test on the Windows platform always fails inexplicably, resulting in the inability to release the binary file, the problem has not been resolved. But as you said, I should temporarily disable testing on Windows to ensure the normal distribution of binary files.

By the way, there is no change in v0.10.1 and v0.10.0, v0.10.1 is only caused by deno.land/x refactoring, and it is invalid, so re-release

**Comment by mocox** [comment]
does this have the same symptoms as this ->

INFO downloading deno plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.10.0/deno_mongo.dll"
error: Uncaught Error: downloading plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.10.0/deno_mongo.dll" failed.
    throw Error(`downloading plugin "${name}" from "${remoteUrl}" failed.`);
          ^
    at downloadFromRemote (mod.ts:76:11)
    at async download (mod.ts:46:7)
    at async prepare (mod.ts:60:21)
    at async init (util.ts:44:3)
    at async mod.ts:13:1

**Comment by lucacasonato** [comment]
v0.12.0 has binary releases
